name: look_after
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  google_sign_in: ^4.5.1
  provider: ^6.0.2
  modal_progress_hud: ^0.1.3
  socket_io_client: ^1.0.2
  intl: ^0.17.0
  flutter_native_splash: ^2.0.2
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  dotted_border: ^2.0.0+2
  timeline_tile: ^2.0.0
  flutter_colorpicker: ^1.0.3
  enough_mail: ^1.3.4

  #  hive database
  hive: ^2.0.3
  hive_flutter: ^1.0.0


  #  Added by hriody
  get: ^4.6.1
  google_fonts:
  date_picker_timeline:
  sqflite:
  flutter_staggered_animations:
  flutter_local_notifications:
  flutter_native_timezone:
#-----------------



flutter_native_splash:
  color: "#ffffff"
  image: images/Look-After-Logo.png
  andriod: true
  ios: true
#  flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
#  run command after changing the img or color

dev_dependencies:
  flutter_test:
    sdk: flutter

#  hive database generator
  hive_generator: ^1.0.1
  build_runner: ^1.12.2

flutter:
  uses-material-design: true

  assets:
    - images/

